README.md

Updated Readme with assignment details and criteria

3 update readme with criterias for assignment

---

package-lock.json
package.json

Fix to make the dev server and vitest run on mac

added dev deps

---

src/data/movies.json

Added movies.json to draw data from in data folder

add movies.json

---

src/data/index.ts
src/main.tsx
src/routes/CategoryPage.tsx

basic logic for category page, no styling

Category page contructions

---

src/routes/CategoryPage.tsx
src/tests/Categories.test.tsx

#24 
Due to testing bug, I've refactored the CategoryPage from a 'select'-element to buttons for each category. functionality works the same.
Tests added for respective elements.
A user should be able to display a list of movies based upon selected genre.
If no genre is chosen, display all movies.

Test for categories

---

src/data/movies.json

#38 
Added missing posters in movies.json to use for background in MovieView

Add missing posters

---

index.html
src/components/HeroSlide.css
src/components/HeroSlide.tsx
src/data/movies.json
src/index.css

#32 
Added styling, icons, new poster in JSON and a label for trending. Take a look and see what you think. 
- a user shall be able to ...
- the page shall...

32 style heroslide

---

src/Movies.tsx
src/data/movies.json
src/index.css
src/main.tsx
src/movies.css
src/routes/HomePage.tsx

Since the project is fairly new none of the info from the movies was rendered yet. 
[Link to the issue here...](https://github.com/Netflix4-0/Netflix4.0/issues/22)
The following functionality has been added: 
* All of the movies are now being rendered
* The movies are being filtered be genre and rendered in rows by each column
* The broken thumbnail links from the JSON file has been replaced
* Added some basic styling to the page to make it looks more like the figma design 
( his is still in progress but will be completed in another issue)
- A user shall be able to see all of the titles and pictures of all the movies from the JSON file, these shall be sorted by each genre

22 render movies on the homepage

---

src/components/HeroSlide.tsx
src/routes/Home.tsx
src/tests/HeroSlide.test.tsx

#40 
Added tests to check that the Heroslide renders correctly.
- Testing so that the title is rendered
- Testing so that the synopsis is rendered
- Testing so that both buttons are rendered
- Testing so that isTrending label is rendered

40 add tests for heroslide

---

src/components/heroSlide/HeroSlide.tsx
src/main.tsx
src/routes/MovieView.tsx

#52
No longer hardcoded, you can now click on movies from the categories page + in the heroslide. 
Will be added in the next issue.

52 add json data to movieview

---

src/tests/HeroSlide.test.tsx
src/tests/MovieView.test.tsx

#58 
Added tests for the MovieView.
Added tests to check the following rendering:
- Title
- Synopsis
- Trending
- Rating
- Year
- Thumbnail
- Actors
- Genres

58 add tests for movieview

---

.github/workflows/node.js.yml

We had no working Ci flow in place so here we try to add it.

create ci flow

---

src/components/heroSlide/HeroSlide.css
src/components/heroSlide/HeroSlide.tsx
src/context/bookmarkContext.tsx

Issue #65
Enhanced HeroSlide functionality to support adding or removing bookmarks.
Resolved the bug in removeBookmark within bookmarkContext that caused the addition of duplicate movies instead of removing bookmarks after a page refresh.
Tests will be incorporated in a later issue.

Bookmark movie in heroslide

---

README.md
src/routes/MovieView.css
src/routes/MovieView.tsx

Addressing problem #74.
Introduced a Bookmark button to MovieView and made corresponding updates to the README.
Testing procedures will be outlined in a separate issue.

Bookmark movie in movieview

---

src/components/header/Header.css
src/components/header/Header.tsx
src/components/heroSlide/HeroSlide.css
src/components/heroSlide/HeroSlide.tsx
src/components/movies/Movies.tsx
src/components/movies/movies.css
src/components/thumbnail/Thumbnail.css
src/components/thumbnail/Thumbnail.tsx

#76
Solved so that Swiper.js is now implemented to the movies in homepage. Also added so that the header now pops up when scrolling up and disappears when scrolling down for easier navigation.
- a user shall be able to ...
- the page shall...

76 add heroslide pagination + carousel to homepage

---

README.md
src/components/footer/Footer.css
src/components/footer/Footer.tsx
src/components/heroSlide/HeroSlide.tsx
src/components/movies/Movies.tsx
src/components/movies/movies.css
src/components/thumbnail/Thumbnail.tsx

#79 
Added a "Recommended for you" carousel  showcasing 10 randomly selected non-trending movies (previous mapping of movies temporarily commented out).
Updated some styling
Replaced logo in footer

79 add recommended for you carousel in homepage

---

src/components/thumbnail/Thumbnail.tsx
src/context/bookmarkContext.tsx
src/routes/Bookmarks.tsx

When refreshing after adding a movie to bookmarks, the remove bookmark function did not work (on the thumbnail component)
Had to change how it filters when something is already in added to bookmarks, so it can run the proper function.

84 bookmarking bug on thumbnail

---

src/components/thumbnail/Thumbnail.tsx
src/routes/CategoryPage.css
src/routes/CategoryPage.tsx
src/tests/Categories.test.tsx
src/tests/Thumbnail.test.tsx

#78 
Refactored multiple buttons to a custom dropdown and implemented correlating tests.
test for dropdown functionality
test for redirection when clicking on thumbnail

Refactor category buttons

---

.github/check-pr.yml
src/hooks/useSessionStorage.ts

[Link to the issue here...](https://github.com/Netflix4-0/Netflix4.0/issues/92)
I added lint into the "check-pr" file to add it to the ci flow, **This change won't work until this PR is merged**
- a PR should not be able to merge if there are any linting errors currently in the project.

added lint to the ci flow and fixed our only lint warning.

---

src/components/footer/Footer.css
src/components/header/Header.css
src/components/heroSlide/HeroSlide.css
src/components/movies/Movies.css
src/components/thumbnail/Thumbnail.css
src/routes/CategoryPage.css
src/routes/ErrorPage.css
src/routes/MovieView.css
src/tests/Bookmarks.test.tsx

We had a mix of px values and rem values in the codebase. 
Convert the pixel values to rem

94 css and test refactoring
